name: CI Build
on:
  push:
    branches:
      - main
      - 'rel/**'
  workflow_dispatch:

jobs:
  build:
    name: "CI Build"
    runs-on: windows-2022
    env:
      DOTNET_NOLOGO: true
    steps:
      - name: Clone source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.0.x
            7.0.x

      - name: Get .NET information
        run: dotnet --info

      - name: "Build target: CI"
        env:
          PublishToken: ${{ secrets.PublishToken }}
          SignClientUser: ${{ secrets.SignClientUser }}
          SignClientSecret: ${{ secrets.SignClientSecret }}
        run: dotnet run --project tools/builder --no-launch-profile -- CI --timing

      - name: "Upload artifact: test"
        uses: actions/upload-artifact@v3
        with:
          name: test
          path: artifacts/test
        if: always()

      - name: "Upload artifact: packages"
        uses: actions/upload-artifact@v3
        with:
          name: packages
          path: artifacts/packages
        if: always()
